export const PERMISSIONS = {
  // Phase 1
  USER_VIEW: "user.view",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  ROLE_VIEW: "role.view",
  ROLE_MANAGE: "role.manage",
  AUDIT_VIEW: "audit.view",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
  DASHBOARD_VIEW: "dashboard.view",
  // Phase 2 — Patient
  PATIENT_VIEW: "patient.view",
  PATIENT_CREATE: "patient.create",
  PATIENT_UPDATE: "patient.update",
  PATIENT_MERGE: "patient.merge",
  // Phase 2 — Reception
  RECEPTION_VIEW: "reception.view",
  RECEPTION_CREATE: "reception.create",
  RECEPTION_UPDATE: "reception.update",
  // Phase 2 — Appointment
  APPOINTMENT_VIEW: "appointment.view",
  APPOINTMENT_CREATE: "appointment.create",
  APPOINTMENT_UPDATE: "appointment.update",
  APPOINTMENT_CANCEL: "appointment.cancel",
  // Phase 2 — Encounter
  ENCOUNTER_VIEW: "encounter.view",
  ENCOUNTER_CREATE: "encounter.create",
  ENCOUNTER_UPDATE: "encounter.update",
  ENCOUNTER_CLOSE: "encounter.close",
  // Phase 2 — Queue
  QUEUE_VIEW: "queue.view",
  QUEUE_CREATE: "queue.create",
  QUEUE_CALL: "queue.call",
  QUEUE_UPDATE: "queue.update",
  QUEUE_COMPLETE: "queue.complete",
  // Phase 2 — Triage
  TRIAGE_VIEW: "triage.view",
  TRIAGE_CREATE: "triage.create",
  // Phase 2 — Consultation
  CONSULTATION_VIEW: "consultation.view",
  CONSULTATION_CREATE: "consultation.create",
  CONSULTATION_UPDATE: "consultation.update",
  CONSULTATION_FINALIZE: "consultation.finalize",
  // Phase 2 — Diagnosis
  DIAGNOSIS_VIEW: "diagnosis.view",
  DIAGNOSIS_CREATE: "diagnosis.create",
  DIAGNOSIS_UPDATE: "diagnosis.update",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMIN: "admin",
  DOCTOR: "doctor",
  NURSE: "nurse",
  RECEPTIONIST: "receptionist",
  LAB_TECH: "lab_technician",
  RADIOLOGIST: "radiologist",
  PHARMACIST: "pharmacist",
  CASHIER: "cashier",
  INVENTORY_OFFICER: "inventory_officer",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionKey[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.DOCTOR]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CONSULTATION_VIEW,
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.CONSULTATION_FINALIZE,
    PERMISSIONS.DIAGNOSIS_VIEW,
    PERMISSIONS.DIAGNOSIS_CREATE,
    PERMISSIONS.DIAGNOSIS_UPDATE,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.ENCOUNTER_UPDATE,
    PERMISSIONS.ENCOUNTER_CLOSE,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.QUEUE_CALL,
    PERMISSIONS.APPOINTMENT_VIEW,
  ],
  [ROLES.NURSE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.TRIAGE_VIEW,
    PERMISSIONS.TRIAGE_CREATE,
    PERMISSIONS.QUEUE_CALL,
    PERMISSIONS.QUEUE_UPDATE,
    PERMISSIONS.QUEUE_COMPLETE,
    PERMISSIONS.QUEUE_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.PATIENT_CREATE,
    PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.PATIENT_MERGE,
    PERMISSIONS.RECEPTION_VIEW,
    PERMISSIONS.RECEPTION_CREATE,
    PERMISSIONS.RECEPTION_UPDATE,
    PERMISSIONS.APPOINTMENT_VIEW,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ENCOUNTER_UPDATE,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.QUEUE_CREATE,
    PERMISSIONS.QUEUE_VIEW,
  ],
  [ROLES.LAB_TECH]: [PERMISSIONS.DASHBOARD_VIEW],
  [ROLES.RADIOLOGIST]: [PERMISSIONS.DASHBOARD_VIEW],
  [ROLES.PHARMACIST]: [PERMISSIONS.DASHBOARD_VIEW],
  [ROLES.CASHIER]: [PERMISSIONS.DASHBOARD_VIEW],
  [ROLES.INVENTORY_OFFICER]: [PERMISSIONS.DASHBOARD_VIEW],
};
