import { pgTable, text, timestamp, date, index } from "drizzle-orm/pg-core";
import { user } from "./auth";

export const patients = pgTable("patients", {
  id: text("id").primaryKey(),
  mrn: text("mrn").notNull().unique(),
  firstName: text("first_name").notNull(),
  middleName: text("middle_name"),
  lastName: text("last_name").notNull(),
  suffix: text("suffix"),
  dateOfBirth: date("date_of_birth").notNull(),
  sex: text("sex").notNull(),
  phone: text("phone"),
  email: text("email"),
  addressLine1: text("address_line1"),
  addressLine2: text("address_line2"),
  city: text("city"),
  province: text("province"),
  postalCode: text("postal_code"),
  country: text("country").default("PH"),
  emergencyContactName: text("emergency_contact_name"),
  emergencyContactPhone: text("emergency_contact_phone"),
  emergencyContactRelationship: text("emergency_contact_relationship"),
  bloodType: text("blood_type"),
  allergies: text("allergies"),
  medicalAlerts: text("medical_alerts"),
  status: text("status").notNull().default("active"),
  photo: text("photo"),
  deletedAt: timestamp("deleted_at"),
  deletedBy: text("deleted_by").references(() => user.id, { onDelete: "set null" }),
  deletionReason: text("deletion_reason"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: text("created_by").references(() => user.id, { onDelete: "set null" }),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  updatedBy: text("updated_by").references(() => user.id, { onDelete: "set null" }),
}, (t) => [
  index("patients_mrn_idx").on(t.mrn),
  index("patients_last_name_idx").on(t.lastName),
  index("patients_dob_idx").on(t.dateOfBirth),
  index("patients_status_idx").on(t.status),
]);
